parameters:
    nelmio_cors_allow_origin: '%env(CORS_ALLOW_ORIGIN)%'

nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%nelmio_cors_allow_origin%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/': ~
